[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "libtmux"
version = "0.8.2"
description = "scripting library / orm for tmux"
license = "MIT"
authors = ["Tony Narlock <tony@git-pull.com>"]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"

[tool.poetry.dev-dependencies]
alagitpull = "*"
black = {version="==19.10b0", python="^3.6"}
doc8 = "*"
docutils = "*"
flake8 = "*"
isort = "*"
pytest = [
  {version="<4.7.0", python="<3"},
  {version="*", python=">=3"}
]
pathlib2 = {version="<2.3.5", python="<3"}  # Untangle pytest peer-dependency
pytest-rerunfailures = "*"
sphinx = [
  {version="<2", python="<3"},
  {version="*", python=">=3"}
]
sphinx-issues = "*"
twine = "*"
codecov = "*"
coverage = "*"
pytest-cov = [
  {version="<2.10.0", python="<3"},
  {version="*", python=">=3"}
]
